import { defineConfig, type IndexHtmlTransformContext } from "vite";
import { fileURLToPath, URL } from "node:url";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

// Is this emitted chunk part of the (large, lazy) CodeMirror editor payload?
// Matched on the chunk's *logical* name (assigned by manualChunks / the lazy
// import), not on the hashed output filename — so it keeps working if the hash
// format or file layout changes. Editor panels are matched by their source
// module id since they don't get a manualChunks name.
function isEditorChunk(chunk: { name?: string; facadeModuleId?: string | null }): boolean {
  const name = chunk.name ?? "";
  if (
    name === "cm" ||
    name === "cm-merge" ||
    name.startsWith("cm-lang-") ||
    name.startsWith("cm-legacy-") ||
    name.startsWith("codemirrorThemes")
  ) {
    return true;
  }
  const src = chunk.facadeModuleId ?? "";
  return /\/(?:EditorPanel|DiffPanel|codemirrorThemes)\b/.test(src);
}

// The CodeMirror runtime is large and is only needed when the user opens an
// editor or diff. Vite can emit `<link rel="modulepreload">` tags for lazy
// chunk dependencies, which turns that lazy editor payload back into startup
// work. Strip those preloads; the dynamic imports still fetch the chunks on
// demand when an editor/diff is actually opened.
//
// We derive the exact filenames to strip from the build's `bundle` (the actual
// emitted chunks) rather than guessing at href patterns with a regex — so a
// rename in `manualChunks` can never silently defeat this optimization.
const dropCmPreload = {
  name: "drop-cm-preload",
  apply: "build" as const,
  transformIndexHtml(html: string, ctx: IndexHtmlTransformContext) {
    const bundle = ctx.bundle;
    if (!bundle) return html;
    const files: string[] = [];
    for (const item of Object.values(bundle)) {
      if (item.type === "chunk" && isEditorChunk(item)) files.push(item.fileName);
    }
    if (files.length === 0) return html;
    // Drop any modulepreload link that points at one of those chunk files.
    return html.replace(
      /<link rel="modulepreload"[^>]*href="([^"]*)"[^>]*>\s*/g,
      (match, href: string) => (files.some((f) => href.endsWith(f)) ? "" : match),
    );
  },
};

// Tauri expects a fixed dev port and produces the frontend into `dist/`.
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    dropCmPreload,
    // Phase 24: Bundle analysis — generates a visualizable stats file
    // when ANALYZE=1 is set, so we can inspect chunk sizes.
    {
      name: "bundle-analysis-report",
      apply: "build" as const,
      generateBundle() {
        if (process.env.ANALYZE !== "1") return;
        // The report is generated by rollup's output; we just mark it.
        console.log("[bundle-analysis] ANALYZE=1 — check dist/ for chunk sizes");
      },
    },
  ],
  clearScreen: false,
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
    // Force a SINGLE instance of every CodeMirror runtime package. The editor
    // statically imports @codemirror/state while the language packs import it
    // again lazily; without dedupe the dev server can load two copies, which
    // breaks CodeMirror's instanceof checks and throws "Unrecognized extension
    // value ([object Promise]) … multiple instances of @codemirror/state" the
    // moment a file is opened.
    dedupe: [
      "@codemirror/state",
      "@codemirror/view",
      "@codemirror/language",
      "@codemirror/commands",
      "@codemirror/search",
      "@codemirror/autocomplete",
      // The editor's lint gutter and the DiffPanel's MergeView both re-import
      // @codemirror/state + view transitively. Pin them too so a stray second
      // copy of the runtime can never sneak in and trip CodeMirror's
      // `instanceof` checks ("multiple instances of @codemirror/state").
      "@codemirror/lint",
      "@codemirror/merge",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
    ],
  },
  // Pre-bundle the CodeMirror core so the dev server doesn't re-optimize (and
  // momentarily double-load @codemirror/state) the first time a file is opened.
  // Only affects `vite dev`; production chunking is handled by manualChunks.
  optimizeDeps: {
    include: [
      "@codemirror/state",
      "@codemirror/view",
      "@codemirror/language",
      "@codemirror/commands",
      "@codemirror/search",
      "@codemirror/autocomplete",
      "@codemirror/lint",
      "@lezer/highlight",
    ],
  },
  server: {
    port: 5173,
    strictPort: true,
    watch: {
      // Don't reload the webview when Rust sources change.
      ignored: ["**/src-tauri/**", "**/crates/**"],
    },
  },
  build: {
    target: "es2022",
    outDir: "dist",
    sourcemap: false,
    // Computing gzip sizes for every chunk noticeably slows each build; we only
    // need it when actually inspecting the bundle (ANALYZE=1).
    reportCompressedSize: Boolean(process.env.ANALYZE),
    // Desktop app loading from disk: big chunks are fine, the warning is noise.
    chunkSizeWarningLimit: 5000,
    // The `drop-cm-preload` plugin is already registered once in the top-level
    // `plugins` array above (it runs at build time via `apply: "build"`), so it
    // intentionally is NOT repeated here.
    rollupOptions: {
      input: {
        main: "index.html",
        tray: "tray.html",
      },
      output: {
        // Split the heavyweights out of the main bundle so the first paint
        // only loads what the initial window actually needs.
        manualChunks(id: string) {
          // CRITICAL: Vite's preload helper is a virtual module; left to
          // Rollup it gets colocated into the (huge) CodeMirror (cm) chunk,
          // which makes the entry *statically* import all of CodeMirror — ~4 MB
          // parsed before first paint. Pin it to the always-loaded vendor chunk.
          if (id.includes("vite/preload-helper") || id.startsWith("\0vite/")) return "vendor";
          if (!id.includes("node_modules")) return undefined;
          // CodeMirror core: kept together so the editor mounts in one network
          // round-trip. Includes @lezer/highlight because the theme builder
          // (codemirrorThemes.ts) and every language pack reference its tag
          // table — splitting it off would force every language to bring its
          // own copy of the same data, bloating the chunks.
          if (id.includes("@codemirror/state") || id.includes("@codemirror/view") || id.includes("@codemirror/commands") || id.includes("@codemirror/search") || id.includes("@codemirror/language") || id.includes("@codemirror/autocomplete") || id.includes("@lezer/common") || id.includes("@lezer/lr") || id.includes("@lezer/highlight") || id.includes("style-mod") || id.includes("crelt")) return "cm";
          // Merge view + gutter for diff panels. Small (~10 KB) but kept
          // separate from the cm core so diffs don't pull in editor deps.
          if (id.includes("@codemirror/merge")) return "cm-merge";
          // Per-language packs: each becomes its own chunk on first use. Rust
          // (≈90 KB) only loads when someone opens a .rs file, Python (≈70 KB)
          // only on .py, etc. The map is intentionally narrow so any
          // @codemirror/* not in the allowlist above still ends up in the cm
          // core and we don't accidentally create dozens of micro-chunks.
          if (id.includes("@codemirror/lang-")) {
            const m = id.match(/@codemirror\/lang-([\w-]+)/);
            return m ? `cm-lang-${m[1]}` : "cm";
          }
          // StreamLanguage grammars (@codemirror/legacy-modes) power shell,
          // toml, ruby, swift, kotlin, lua, etc. Each lands in its own chunk
          // fetched on first use of that language — never at startup.
          if (id.includes("@codemirror/legacy-modes")) {
            const m = id.match(/legacy-modes\/mode\/([\w-]+)/);
            return m ? `cm-legacy-${m[1]}` : "cm-legacy";
          }
          // Per-language Lezer grammars (@lezer/cpp, @lezer/php, @lezer/xml, …)
          // are pulled in ONLY by their lazy lang pack. Keep the shared lezer
          // runtime in the cm core, but route each grammar to its language
          // chunk so it stays off the startup critical path (never "vendor").
          if (id.includes("@lezer/")) {
            if (
              id.includes("@lezer/common") ||
              id.includes("@lezer/lr") ||
              id.includes("@lezer/highlight")
            )
              return "cm";
            const m = id.match(/@lezer\/([\w-]+)/);
            return m ? `cm-lang-${m[1]}` : "cm";
          }
          if (id.includes("@xterm")) return "xterm";
          if (id.includes("dockview")) return "dockview";
          if (id.includes("react-dom") || id.includes("/react/") || id.includes("scheduler")) return "react";
          // Keep lucide in its own chunk. Removing this directive just hoists
          // every icon into the always-preloaded `vendor` chunk (net-worse for
          // startup); properly trimming the startup icon set (plan item #14)
          // needs per-component import surgery, not a chunking tweak.
          if (id.includes("lucide")) return "icons";
          if (id.includes("marked") || id.includes("highlight") || id.includes("dompurify") || id.includes("shiki"))
            return "markdown";
          return "vendor";
        },
      },
    },
  },
});
