//! Luxor Tauri application: thin IPC layer over `luxor-core`.

mod autostart;
mod commands;
mod pathguard;
mod state;

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, RwLock};

use luxor_core::projects::Registry;
use luxor_core::pty::{OutputSink, PtyEvent, PtyManager};
use tauri::{Emitter, Manager};

use state::AppState;

/// Event names shared with the frontend (see `src/lib/ipc.ts`).
pub const EVENT_PTY_OUTPUT: &str = "luxor://pty-output";
pub const EVENT_PTY_EXIT: &str = "luxor://pty-exit";

/// Crisp, purpose-sized app icons embedded as raw RGBA8 (top-down, row-major).
/// Set explicitly on the tray (32px) and main window (128px) via
/// `tauri::image::Image::new`, so Windows scales from a small source instead of
/// soft-scaling the bundled 256px icon down to ~16-32px (which looked blurry
/// next to other taskbar/tray icons). The tray source is a dedicated 32px glyph
/// with thickened strokes so it stays sharp when the OS scales it to the
/// 16-24px tray (a 64px source soft-scaled to those sizes read muddy).
/// Regenerated by `gen_icons.py`.
const TRAY_ICON_RGBA: &[u8] = include_bytes!("../icons/tray-icon.rgba");
const WIN_ICON_RGBA: &[u8] = include_bytes!("../icons/win-icon.rgba");

#[derive(serde::Serialize, Clone)]
struct PtyOutputPayload {
    session_id: String,
    /// Raw bytes, base64-encoded (terminal output is not guaranteed UTF-8).
    data_b64: String,
}

#[derive(serde::Serialize, Clone)]
struct PtyExitPayload {
    session_id: String,
    exit_code: Option<u32>,
}

/// Event emitted when the user picks a project in the tray menu.
pub const EVENT_OPEN_PROJECT: &str = "luxor://open-project-request";

/// The tray uses a custom popup window (`show_tray_popup`) instead of a native
/// OS menu, so there is no native menu to rebuild. Kept as a no-op so existing
/// callers (config save + project-list sync) stay valid without reintroducing a
/// right-click system menu.
pub(crate) fn refresh_tray_menu(_app: &tauri::AppHandle) {}

/// Open the local-first telemetry store at its default path. If that fails
/// (e.g. unwritable config dir), fall back to a temp-dir copy so the app still
/// launches — telemetry is best-effort and must never block startup.
fn open_telemetry_store() -> luxor_core::telemetry::TelemetryStore {
    use luxor_core::telemetry::TelemetryStore;
    let path = TelemetryStore::default_path()
        .unwrap_or_else(|_| std::env::temp_dir().join("luxor-local_stats.db"));
    match TelemetryStore::open(&path) {
        Ok(store) => store,
        Err(e) => {
            tracing::warn!("telemetry store unavailable at {}: {e}; using temp", path.display());
            // Use a per-process file so a stale/corrupt fallback from another
            // instance cannot prevent startup. If temp storage is unavailable
            // too, keep analytics ephemeral rather than crashing the whole app.
            let tmp = std::env::temp_dir().join(format!(
                "luxor-local_stats-{}.db",
                std::process::id()
            ));
            TelemetryStore::open(&tmp).unwrap_or_else(|temp_error| {
                tracing::error!(
                    "telemetry temp store unavailable at {}: {temp_error}; using memory",
                    tmp.display()
                );
                TelemetryStore::open_in_memory().unwrap_or_else(|memory_error| {
                    panic!("failed to initialize SQLite even in memory: {memory_error}")
                })
            })
        }
    }
}

/// Ensure the custom tray popup window exists (created lazily on first click).
/// The window is borderless, transparent, always-on-top, skips the taskbar,
/// and starts hidden. `show_tray_popup` positions and reveals it.
fn ensure_tray_popup(app: &tauri::AppHandle) -> tauri::Result<()> {
    use tauri::{WebviewUrl, WebviewWindowBuilder};
    if app.get_webview_window("tray-popup").is_some() {
        return Ok(());
    }
    WebviewWindowBuilder::new(app, "tray-popup", WebviewUrl::App("tray.html".into()))
        .decorations(false)
        .transparent(true)
        .always_on_top(true)
        .skip_taskbar(true)
        .resizable(false)
        .visible(false)
        .shadow(false)
        .inner_size(264.0, 360.0)
        .build()?;
    Ok(())
}

/// Position the tray popup near the last tray click, given the popup's logical
/// size. Anchors to the left of the cursor when there's room (Windows tray sits
/// bottom-right) and places it above the cursor, clamped inside the monitor.
/// Shared by `show_tray_popup` and the `tray_popup_fit` command (which the
/// frontend calls after it has measured the menu's real height).
pub(crate) fn position_tray_popup(
    win: &tauri::WebviewWindow,
    cursor: (f64, f64),
    w_log: f64,
    h_log: f64,
) {
    let monitor = win.current_monitor().ok().flatten();
    let (x, y) = if let Some(m) = monitor {
        let scale = m.scale_factor();
        let mon_pos = m.position();
        let mon_size = m.size();
        let cursor_x_log = cursor.0 / scale;
        let cursor_y_log = cursor.1 / scale;
        let mon_x = mon_pos.x as f64 / scale;
        let mon_y = mon_pos.y as f64 / scale;
        let mon_w = mon_size.width as f64 / scale;
        let mon_h = mon_size.height as f64 / scale;
        // Anchor the popup's RIGHT edge slightly to the right of the cursor
        // (+12px) so the window sits under the tray icon instead of drifting
        // left away from it. Clamp inside the monitor so it never goes off-screen.
        let x = (cursor_x_log - w_log + 12.0)
            .max(mon_x)
            .min(mon_x + mon_w - w_log);
        let y = (cursor_y_log - h_log - 8.0)
            .max(mon_y)
            .min(mon_y + mon_h - h_log);
        (x, y)
    } else {
        (cursor.0 - w_log - 8.0, cursor.1 - h_log - 8.0)
    };
    let _ = win.set_position(tauri::LogicalPosition::new(x, y));
}

/// True while the tray popup is inside its short post-show grace window.
/// Auto-hide paths (main-window focus regain, cursor-outside checks) must not
/// dismiss the popup during this window: on Windows, `show` + `set_focus` on a
/// transparent always-on-top window causes focus to bounce through the main
/// window, which previously hid the menu before it ever painted.
pub(crate) fn tray_popup_in_grace(app: &tauri::AppHandle) -> bool {
    const GRACE: std::time::Duration = std::time::Duration::from_millis(800);
    app.try_state::<AppState>()
        .and_then(|state| {
            *state
                .tray_popup_shown_at
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner)
        })
        .map(|shown| shown.elapsed() < GRACE)
        .unwrap_or(false)
}

/// True when the global cursor is outside a native window's physical bounds.
fn cursor_outside_window(win: &tauri::WebviewWindow, padding: f64) -> Option<bool> {
    let pos = win.outer_position().ok()?;
    let size = win.outer_size().ok()?;
    let cursor = win.cursor_position().ok()?;
    let pad = padding.max(0.0);
    let left = pos.x as f64 - pad;
    let top = pos.y as f64 - pad;
    let right = pos.x as f64 + size.width as f64 + pad;
    let bottom = pos.y as f64 + size.height as f64 + pad;
    Some(cursor.x < left || cursor.x > right || cursor.y < top || cursor.y > bottom)
}

/// Toggle the custom tray popup near the tray icon. If it is already visible,
/// hide it (so a second right-click dismisses it — this also rescues the
/// "menu won't go away" case where the popup never received a blur event).
/// Otherwise position it near the cursor and reveal it.
/// `cursor` is the physical screen position from the tray click event.
fn show_tray_popup(app: &tauri::AppHandle, cursor: tauri::PhysicalPosition<f64>) {
    use tauri::Manager;
    // Remember the click position so the frontend can re-anchor the popup
    // after it resizes the window to fit the (config-dependent) menu height.
    if let Some(state) = app.try_state::<AppState>() {
        *state
            .tray_cursor
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner) = Some((cursor.x, cursor.y));
    }
    if let Err(e) = ensure_tray_popup(app) {
        tracing::warn!("failed to create tray popup: {e}");
        return;
    }
    if let Some(win) = app.get_webview_window("tray-popup") {
        // Second click while open → dismiss.
        if win.is_visible().unwrap_or(false) {
            let _ = win.hide();
            return;
        }
        let scale = win.scale_factor().unwrap_or(1.0);
        let size = win.outer_size().unwrap_or(tauri::PhysicalSize {
            width: 264,
            height: 360,
        });
        position_tray_popup(
            &win,
            (cursor.x, cursor.y),
            size.width as f64 / scale,
            size.height as f64 / scale,
        );
        // Record the show instant BEFORE revealing the window: every auto-hide
        // path checks `tray_popup_in_grace` against it, so the focus churn that
        // show/set_focus trigger can never dismiss the menu instantly.
        if let Some(state) = app.try_state::<AppState>() {
            *state
                .tray_popup_shown_at
                .lock()
                .unwrap_or_else(std::sync::PoisonError::into_inner) =
                Some(std::time::Instant::now());
        }
        let _ = win.show();
        // Take focus on show. This is what makes "click anywhere else closes
        // it" work even when the user moves to a *third-party* application: a
        // focused popup loses focus the instant another window is activated,
        // which the watchdog below can observe. (Previously the popup was shown
        // unfocused to dodge focus churn, but then nothing could detect the user
        // interacting with non-Luxor windows, so the menu lingered on screen.)
        let _ = win.set_focus();
        // Launch the focus-loss watchdog tied to this show. The brief focus
        // churn that `set_focus` causes for transparent always-on-top windows is
        // absorbed by the watchdog's grace period, so the menu no longer "appears
        // and instantly disappears".
        if let Some(state) = app.try_state::<AppState>() {
            let my_gen = state
                .tray_popup_gen
                .fetch_add(1, Ordering::SeqCst)
                .wrapping_add(1);
            spawn_tray_popup_watchdog(app, my_gen);
        }
    }
}

/// Close the tray popup the moment it stops being the focused window.
///
/// The popup is transparent, borderless and always-on-top; on Windows such
/// utility windows frequently never deliver a `Focused(false)` *event* when the
/// user clicks into another application — which is exactly why the menu used to
/// linger while the user "just surfed other windows". This short-lived thread
/// polls `is_focused()` instead: a level check that does not depend on a single
/// edge event arriving, and so it catches the focus change even when the event
/// is dropped.
///
/// Safeguards:
/// * A grace window after show absorbs the brief focus churn that `set_focus`
///   triggers for transparent always-on-top windows (the old "appear and
///   instantly disappear" bug).
/// * It only auto-closes once the popup has actually *held* focus at least once.
///   On platforms / window managers where the transparent popup never accepts
///   focus, the thread leaves it alone and the existing click-outside, cursor
///   and Esc paths keep working unchanged — i.e. no regression.
/// * `my_gen` ties the thread to one specific show; a newer show, or the popup
///   becoming invisible, makes it exit, so only one watchdog is ever live.
fn spawn_tray_popup_watchdog(app: &tauri::AppHandle, my_gen: u64) {
    use std::time::{Duration, Instant};
    let app = app.clone();
    std::thread::spawn(move || {
        let shown_at = Instant::now();
        let grace = Duration::from_millis(450);
        let mut had_focus = false;
        loop {
            std::thread::sleep(Duration::from_millis(100));
            let Some(state) = app.try_state::<AppState>() else {
                return;
            };
            if state.tray_popup_gen.load(Ordering::SeqCst) != my_gen {
                return; // superseded by a newer show
            }
            let Some(win) = app.get_webview_window("tray-popup") else {
                return;
            };
            if !win.is_visible().unwrap_or(false) {
                return; // already hidden by another close path
            }
            let focused = win.is_focused().unwrap_or(false);
            if focused {
                had_focus = true;
            }
            // Ignore the initial show/focus handoff churn.
            if shown_at.elapsed() < grace {
                continue;
            }
            // Focus has demonstrably moved to another window → dismiss, but only
            // once the pointer is genuinely outside the popup too. That second
            // condition guards the rare case where `set_focus` doesn't "stick"
            // (focus bounces straight back to the previously active window): we
            // must not yank away a menu the user is still pointing at. When the
            // user actually surfs to another window the cursor follows, so this
            // stays responsive for the real "I'm done with it" case.
            if had_focus && !focused && cursor_outside_window(&win, 2.0).unwrap_or(true) {
                let _ = win.hide();
                return;
            }
        }
    });
}

/// True when `label` belongs to a full app window (`main`, `main-2`, …) as
/// opposed to auxiliary windows like the browser.
fn is_app_window(label: &str) -> bool {
    label == "main" || label.starts_with("main-")
}

/// Best-effort final cleanup for full app quit: kill managed PTYs and remove
/// the CLI single-instance pid file. This runs both on explicit tray quit and
/// on the Tauri exit event so a hidden tray app does not linger as a
/// folder-locking process after the user asked it to quit.
pub(crate) fn cleanup_before_exit(app: &tauri::AppHandle) {
    if let Some(state) = app.try_state::<AppState>() {
        state.pty.shutdown();
    }
    if let Ok(base) = luxor_core::cli::default_base_dir() {
        if let Err(e) = luxor_core::cli::remove_pid_file(&base) {
            tracing::warn!("failed to remove Luxor pid file on shutdown: {e}");
        }
    }
}

/// Show a one-time OS notification the first time the window is hidden to the
/// tray, so the user understands Luxor is still running (terminals and agents
/// keep working) rather than thinking it crashed or quit. Throttled to once per
/// app run via `AppState::tray_hint_shown`, and best-effort: any failure to
/// post the notification is swallowed (the close itself must never be blocked).
/// The text follows the configured UI language.
fn notify_hidden_to_tray(app: &tauri::AppHandle) {
    use tauri_plugin_notification::NotificationExt;

    let Some(state) = app.try_state::<AppState>() else {
        return;
    };
    // Only the first close-to-tray of this session shows the hint.
    if state.tray_hint_shown.swap(true, Ordering::SeqCst) {
        return;
    }
    let is_ru = state
        .config
        .read()
        .map(|c| c.ui.language == "ru")
        .unwrap_or(false);
    let (title, body) = if is_ru {
        (
            "Luxor свёрнут в трей",
            "Окно закрыто, но Luxor продолжает работать в трее — терминалы и агенты активны. Кликните по иконке в трее, чтобы открыть окно снова, или выберите «Выход» в её меню.",
        )
    } else {
        (
            "Luxor is still running",
            "The window closed to the tray — terminals and agents keep working. Click the tray icon to reopen it, or choose Quit from its menu.",
        )
    };
    let _ = app.notification().builder().title(title).body(body).show();
}

fn pty_sink(app: tauri::AppHandle) -> OutputSink {
    use base64::Engine;
    Arc::new(move |event: PtyEvent| match event {
        PtyEvent::Output { session_id, bytes } => {
            let payload = PtyOutputPayload {
                session_id,
                data_b64: base64::engine::general_purpose::STANDARD.encode(bytes),
            };
            // Terminals live only in the main window, so target it directly
            // instead of broadcasting to every webview (tray-popup,
            // luxor-browser) that would just discard the high-volume stream.
            if let Err(e) = app.emit_to("main", EVENT_PTY_OUTPUT, payload) {
                tracing::warn!("failed to emit pty output: {e}");
            }
        }
        PtyEvent::Exited {
            session_id,
            exit_code,
        } => {
            let payload = PtyExitPayload {
                session_id,
                exit_code,
            };
            if let Err(e) = app.emit_to("main", EVENT_PTY_EXIT, payload) {
                tracing::warn!("failed to emit pty exit: {e}");
            }
        }
    })
}

/// Handle `luxor [path]` / `--help` / `--version` invocations that should not
/// start (another) GUI. Returns `true` when this process is done and should
/// exit; `false` when the GUI should start (setup() then queues any argv path).
pub fn cli_handoff() -> bool {
    let mut args = std::env::args().skip(1);
    let Some(arg) = args.next() else {
        return false;
    };
    match arg.as_str() {
        "--version" | "-V" => {
            println!("luxor {}", env!("CARGO_PKG_VERSION"));
            return true;
        }
        "--help" | "-h" => {
            println!(
                "Luxor — an open-source cockpit for AI-assisted coding\n\n\
                 Usage: luxor [path]\n\n\
                 Opens the given folder (e.g. `luxor .`) as a project. When Luxor is\n\
                 already running, the folder opens in the running instance."
            );
            return true;
        }
        _ => {}
    }
    if arg.starts_with('-') {
        return false; // unknown flag: start the GUI normally
    }
    let Ok(base) = luxor_core::cli::default_base_dir() else {
        return false;
    };
    let running = luxor_core::cli::read_app_pid(&base)
        .filter(|pid| *pid != std::process::id())
        .is_some_and(luxor_core::cli::pid_alive);
    if !running {
        return false; // no live instance: start the GUI, setup() queues the path
    }
    let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    match luxor_core::cli::resolve_open_path(&arg, &cwd) {
        Ok(path) => {
            if let Err(e) = luxor_core::cli::push_request(&base, &path) {
                eprintln!("luxor: failed to hand the path to the running instance: {e}");
            } else {
                println!("Opening {} in the running Luxor instance…", path.display());
            }
            true
        }
        Err(e) => {
            eprintln!("luxor: {e}");
            true
        }
    }
}

/// Build and run the Tauri application.
pub fn run() {
    // Crash reporter: persist panics to the config dir so users can attach
    // them to bug reports (Health panel lists them).
    let default_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(move |info| {
        let report = luxor_core::crashlog::format_panic(info, env!("CARGO_PKG_VERSION"));
        let _ = luxor_core::crashlog::write_crash(&report);
        default_hook(info);
    }));

    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                // `luxor_core` must be listed explicitly: the `luxor` directive
                // only matches `luxor::*` targets, not the `luxor_core` crate,
                // so its debug logs (Discord RPC etc.) were filtered out.
                .unwrap_or_else(|_| "info,luxor=debug,luxor_core=debug".into()),
        )
        .init();

    tauri::Builder::default()
        // Single-instance guard (audit 10.2): a second GUI launch focuses the
        // existing window instead of racing it for config.toml/local_stats.db.
        // When the second launch carried a path argument (`luxor <path>`),
        // resolve and emit it as a `cli:open` event immediately — the frontend
        // listens for it, so `luxor .` opens without waiting for the poll
        // interval (audit 10.3).
        .plugin(tauri_plugin_single_instance::init(|app, args, cwd| {
            use tauri::{Emitter, Manager};
            if let Some(w) = app.get_webview_window("main") {
                let _ = w.show();
                let _ = w.unminimize();
                let _ = w.set_focus();
            }
            let arg = args.iter().skip(1).find(|a| !a.starts_with('-'));
            if let Some(arg) = arg {
                let cwd = std::path::PathBuf::from(cwd);
                if let Ok(path) = luxor_core::cli::resolve_open_path(arg, &cwd) {
                    let _ = app.emit("cli:open", path.to_string_lossy().to_string());
                }
            }
        }))
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .setup(|app| {
            // Startup IO fan-out: every step before `app.manage(AppState)`
            // blocks the Tauri event loop, which in turn delays the moment
            // the OS window is created and the webview can start fetching
            // index.html. Three of those steps each touch the disk
            // independently:
            //   * config.toml          (`load_or_recover`)
            //   * the presets directory (creates it on first launch)
            //   * the projects SQLite DB (`Registry::open` + migrations)
            // They have no data dependencies, so we spawn them on background
            // threads and join. On cold storage / Windows Defender first-scan
            // the SQLite open alone can take a few hundred ms; running these
            // serially used to add that to every cold start. Doing them in
            // parallel makes the critical path = max(t_config, t_presets,
            // t_registry) rather than their sum.
            let config_path = luxor_core::config::config_file_path()?;
            let config_path_for_thread = config_path.clone();
            let config_handle = std::thread::spawn(move || {
                // Never refuse to start because of a broken config: back it
                // up and fall back to defaults (the backup path is logged).
                luxor_core::config::load_or_recover(&config_path_for_thread)
            });
            let presets_handle = std::thread::spawn(luxor_core::layout::presets_dir);
            let registry_handle = std::thread::spawn(|| {
                luxor_core::projects::db_path().and_then(|p| Registry::open(&p))
            });
            // `join()` errs only if the worker thread itself panicked. Turn
            // that into a clean setup() error instead of a second panic so
            // the user gets an error dialog rather than a silent crash
            // (audit 4.3); the panic payload is preserved in the message.
            fn join_or_err<T>(
                handle: std::thread::JoinHandle<T>,
                what: &str,
            ) -> std::result::Result<T, Box<dyn std::error::Error>> {
                handle.join().map_err(|panic| {
                    let msg = panic
                        .downcast_ref::<&str>()
                        .map(|s| (*s).to_string())
                        .or_else(|| panic.downcast_ref::<String>().cloned())
                        .unwrap_or_else(|| "unknown panic".into());
                    format!("startup worker '{what}' panicked: {msg}").into()
                })
            }
            let (config, recovered) = join_or_err(config_handle, "config load")?;
            if let Some(backup) = recovered {
                tracing::warn!(
                    "config.toml was corrupt; backed it up to {} and loaded defaults",
                    backup.display()
                );
            }
            let presets_dir = join_or_err(presets_handle, "presets dir")??;
            let registry = join_or_err(registry_handle, "registry open")??;
            let pty = PtyManager::new(pty_sink(app.handle().clone()));

            let launch_on_startup = config.ui.launch_on_startup;
            app.manage(AppState {
                config: RwLock::new(config),
                config_path,
                presets_dir,
                registry: Mutex::new(registry),
                pty,
                stats: Mutex::new(luxor_core::stats::StatsSampler::new()),
                agents: Mutex::new(luxor_core::agents::AgentSampler::new()),
                telemetry: Mutex::new(open_telemetry_store()),
                discord: Mutex::new(commands::discord::DiscordEngine::new()),
                audit_last: Mutex::new(std::collections::HashMap::new()),
                tray_projects: Mutex::new(Vec::new()),
                tray_cursor: Mutex::new(None),
                tray_popup_gen: AtomicU64::new(0),
            tray_popup_shown_at: Mutex::new(None),
                tray_hint_shown: std::sync::atomic::AtomicBool::new(false),
            });
            // Background telemetry retention (plan part 7.2). Off the UI thread.
            commands::telemetry::spawn_background(app.handle().clone());
            // Sync the OS login-startup entry OFF the startup critical path.
            // On Windows this spawns `reg.exe`; running it inline in `setup`
            // blocks the Tauri event loop — and therefore serving index.html to
            // the webview — on *every* launch. It does not need to finish before
            // the window appears, so defer it to a worker thread.
            std::thread::spawn(move || {
                if let Err(e) = autostart::set_enabled(launch_on_startup) {
                    tracing::warn!("failed to sync login startup setting: {e}");
                }
            });

            // Failsafe: never leave the user staring at nothing. If the
            // frontend fails to call `window_ready` quickly (slow paint, JS
            // error before mount), show the window anyway.
            //
            // The window background is `#101014` (same as the inline HTML
            // splash), so revealing before the splash paints shows a dark
            // frame, not a white flash — we can afford to reveal almost
            // immediately. On cold WebView2 boot (5–7 s observed in v0.6.12
            // diagnostics) the previous 450 ms watchdog still meant the user
            // saw a hidden window for several seconds; dropping it to ~80 ms
            // means the dark frame appears the moment Tauri finishes building
            // the window, regardless of how long the bundle takes to parse.
            {
                let handle = app.handle().clone();
                std::thread::spawn(move || {
                    std::thread::sleep(std::time::Duration::from_millis(80));
                    if let Some(win) = handle.get_webview_window("main") {
                        if !win.is_visible().unwrap_or(true) {
                            let _ = win.show();
                        }
                    }
                });
            }

            // `luxor <path>` CLI handshake: record this instance's pid and
            // queue a path passed on our own argv (first launch case). A
            // second `luxor .` while we run only appends to the requests
            // file, which the frontend polls via `cli_poll_requests`.
            //
            // Done on a worker thread: it touches the filesystem (pid file +
            // request queue) and must not sit on the startup critical path that
            // delays the first webview paint. The frontend polls the queue
            // every few seconds, so a few ms of latency here is invisible.
            std::thread::spawn(move || match luxor_core::cli::default_base_dir() {
                Ok(base) => {
                    if let Err(e) = luxor_core::cli::write_pid_file(&base) {
                        tracing::warn!("failed to write app pid file: {e}");
                    }
                    let arg = std::env::args().nth(1).filter(|a| !a.starts_with('-'));
                    if let Some(arg) = arg {
                        let cwd = std::env::current_dir()
                            .unwrap_or_else(|_| std::path::PathBuf::from("."));
                        match luxor_core::cli::resolve_open_path(&arg, &cwd) {
                            Ok(path) => {
                                if let Err(e) = luxor_core::cli::push_request(&base, &path) {
                                    tracing::warn!("failed to queue CLI open request: {e}");
                                }
                            }
                            Err(e) => tracing::warn!("ignoring CLI path argument: {e}"),
                        }
                    }
                }
                Err(e) => tracing::warn!("CLI handshake disabled: {e}"),
            });

            // Discord presence heartbeat. The carousel is normally ticked by
            // the frontend driver (analytics.ts), but WebView2 throttles JS
            // timers once the window is hidden to the tray or minimized —
            // presence then froze on one frame and eventually went stale (part
            // of the "Discord RPC doesn't work" report). This backend thread
            // replays the last received context whenever the frontend has been
            // quiet for 15s+, keeping rotation and reconnect-with-backoff
            // alive while the app sits in the tray. It exits with the process;
            // the engine's own `enabled` flag gates all actual IPC work.
            {
                let handle = app.handle().clone();
                std::thread::spawn(move || {
                    let quiet_after = std::time::Duration::from_secs(15);
                    loop {
                        std::thread::sleep(std::time::Duration::from_secs(10));
                        let Some(state) = handle.try_state::<AppState>() else {
                            continue;
                        };
                        state
                            .discord
                            .lock()
                            .unwrap_or_else(std::sync::PoisonError::into_inner)
                            .heartbeat(quiet_after);
                    }
                });
            }

            // System tray: left-click brings the app to the foreground,
            // right-click opens Luxor's own custom popup (see `show_tray_popup`).
            // No native OS menu is attached, so right-click never shows the
            // system context menu.
            {
                use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};

                let mut tray = TrayIconBuilder::with_id("main-tray")
                    .tooltip(format!("Luxor {}", app.package_info().version))
                    .on_tray_icon_event(|tray, event| {
                        let TrayIconEvent::Click {
                            button,
                            button_state: MouseButtonState::Up,
                            position,
                            ..
                        } = event
                        else {
                            return;
                        };
                        let app = tray.app_handle();
                        match button {
                            // Left-click → restore / focus the main window.
                            // It deliberately does NOT open the popup.
                            MouseButton::Left => {
                                if let Some(win) = app.get_webview_window("main") {
                                    let _ = win.show();
                                    let _ = win.unminimize();
                                    let _ = win.set_focus();
                                }
                            }
                            // Right-click → toggle Luxor's custom tray popup.
                            MouseButton::Right => show_tray_popup(app, position),
                            MouseButton::Middle => {}
                        }
                    });
                // Crisp tray icon: a dedicated 32px source with thickened glyph
                // strokes. Windows scales it down to the 16-24px tray cleanly
                // (a 64px source soft-scaled to those sizes read blurry/muddy
                // next to other apps, and the thin strokes washed out entirely).
                tray = tray.icon(tauri::image::Image::new(TRAY_ICON_RGBA, 32, 32));
                tray.build(app)?;

                // Pre-build the popup window (hidden) so the first right-click
                // reveals it instantly instead of paying webview-creation cost
                // on the click itself — but DEFERRED off the startup critical
                // path. Creating a second WebView2 window inside `setup()` runs
                // BEFORE the main window is even created and used to add a big
                // chunk of the cold-start time on Windows. We now wait a few
                // seconds after launch, then create it from the main thread
                // (window creation must happen there). If the user right-clicks
                // the tray before this fires, `show_tray_popup` creates the
                // popup on demand — a one-time ~100-300 ms delay at worst.
                let handle = app.handle().clone();
                std::thread::spawn(move || {
                    std::thread::sleep(std::time::Duration::from_secs(3));
                    let _ = handle.clone().run_on_main_thread(move || {
                        if let Err(e) = ensure_tray_popup(&handle) {
                            tracing::warn!("failed to pre-create tray popup: {e}");
                        }
                    });
                });
            }

            // Override the taskbar / Alt-Tab window icon with a crisp 128px
            // source. The bundled icon embeds a 256px frame that Windows
            // soft-scales down to the ~24-32px taskbar size; scaling from 128px
            // (with a glyph that now fills the tile) renders noticeably sharper.
            if let Some(win) = app.get_webview_window("main") {
                if let Err(e) = win.set_icon(tauri::image::Image::new(WIN_ICON_RGBA, 128, 128)) {
                    tracing::warn!("failed to set main window icon: {e}");
                }
            }
            Ok(())
        })
        .on_window_event(|window, event| match event {
            // Dismiss the tray popup when a main app window takes focus (the
            // user clicked back into Luxor). Focus *loss* of the popup itself is
            // handled by the watchdog spawned in `show_tray_popup`, which adds a
            // grace period and a "must have held focus first" gate so the
            // `set_focus` churn on transparent always-on-top windows cannot make
            // the menu appear and instantly disappear.
            tauri::WindowEvent::Focused(focused) => {
                let label = window.label();
                if *focused && is_app_window(label) {
                    let app = window.app_handle();
                    // Grace window: right after the popup is shown, focus can
                    // bounce through the main window (set_focus churn on a
                    // transparent always-on-top window). Hiding here would
                    // dismiss the menu before the user ever sees it.
                    if !tray_popup_in_grace(app) {
                        if let Some(popup) = app.get_webview_window("tray-popup") {
                            if popup.is_visible().unwrap_or(false) {
                                let _ = popup.hide();
                            }
                        }
                    }
                }
            }
            // Closing the main window hides it to the tray when enabled —
            // terminals and agents keep running in the background; nothing is
            // lost. Quit explicitly via the tray menu. Secondary app windows
            // (`main-2`, …) just close normally.
            tauri::WindowEvent::CloseRequested { api, .. } => {
                if window.label() == "main" {
                    let keep_running = window
                        .app_handle()
                        .try_state::<AppState>()
                        .map(|state| {
                            state
                                .config
                                .read()
                                .unwrap_or_else(std::sync::PoisonError::into_inner)
                                .ui
                                .close_to_tray
                        })
                        .unwrap_or(false);
                    if keep_running {
                        api.prevent_close();
                        let _ = window.hide();
                        // Tell the user where the window went — once per run.
                        notify_hidden_to_tray(window.app_handle());
                    }
                }
            }
            tauri::WindowEvent::Destroyed => {
                if is_app_window(window.label()) {
                    // Kill all shells only when the last app window is truly
                    // gone (a second window may still own live terminals).
                    let app = window.app_handle();
                    let label = window.label().to_string();
                    let others_alive = app
                        .webview_windows()
                        .keys()
                        .any(|l| is_app_window(l) && *l != label);
                    if !others_alive {
                        cleanup_before_exit(app);
                        app.exit(0);
                    }
                }
            }
            _ => {}
        })
        .invoke_handler(tauri::generate_handler![
            // config
            commands::config::config_get,
            commands::config::config_set,
            // layout presets
            commands::layout::layout_list,
            commands::layout::layout_get,
            commands::layout::layout_save,
            commands::layout::layout_delete,
            // projects
            commands::projects::project_add,
            commands::projects::project_add_blank,
            commands::projects::project_list,
            commands::projects::project_get,
            commands::projects::project_update,
            commands::projects::project_remove,
            commands::projects::project_reorder,
            commands::projects::project_touch,
            commands::projects::recent_list,
            commands::projects::recent_delete,
            // kanban tasks
            commands::projects::task_list,
            commands::projects::task_add,
            commands::projects::task_update,
            commands::projects::task_move,
            commands::projects::task_delete,
            // agent skills
            commands::skills::skills_scan,
            commands::skills::skills_copy,
            commands::skills::skills_import,
            commands::skills::skills_global_root,
            commands::skills::skills_set_enabled,
            commands::skills::skills_remove,
            // skills market
            commands::market::market_catalog,
            commands::market::market_search,
            commands::market::market_skill_md,
            // terminals
            commands::pty::pty_spawn,
            commands::pty::pty_write,
            commands::pty::pty_resize,
            commands::pty::pty_kill,
            commands::pty::pty_list,
            commands::pty::pty_detect_shells,
            // git
            commands::git::git_discover_root,
            commands::git::git_status,
            commands::git::git_blame,
            commands::git::git_log,
            commands::git::git_file_history,
            commands::git::git_commit_files,
            commands::git::git_commit_stats,
            commands::git::git_file_diff,
            commands::git::git_branches,
            commands::git::git_stage,
            commands::git::git_unstage,
            commands::git::git_discard,
            commands::git::git_commit,
            commands::git::git_last_commit_message,
            commands::git::git_branch_create,
            commands::git::git_branch_checkout,
            commands::git::git_branch_delete,
            commands::git::git_stash_save,
            commands::git::git_stash_list,
            commands::git::git_stash_apply,
            commands::git::git_stash_pop,
            commands::git::git_stash_drop,
            commands::git::git_fetch,
            commands::git::git_pull,
            commands::git::git_push,
            commands::git::git_token_set,
            commands::git::git_token_delete,
            commands::git::git_token_exists,
            // filesystem / viewers
            commands::fsx::fs_list_dir,
            commands::fsx::fs_search,
            commands::fsx::fs_read_text,
            commands::fsx::fs_write_text,
            commands::fsx::fs_read_base64,
            commands::fsx::fs_create_file,
            commands::fsx::fs_create_dir,
            commands::fsx::fs_rename,
            commands::fsx::fs_delete,
            commands::fsx::fs_copy,
            commands::fsx::db_tables,
            commands::fsx::db_rows,
            commands::fsx::db_table_info,
            commands::fsx::db_update_cell,
            commands::fsx::db_insert_row,
            commands::fsx::db_delete_rows,
            // stats
            commands::stats::stats_sample,
            commands::stats::stats_ping,
            // telemetry (local activity analytics)
            commands::telemetry::telemetry_record,
            commands::telemetry::telemetry_git_event,
            commands::telemetry::telemetry_bump_audit,
            commands::telemetry::telemetry_dashboard,
            commands::telemetry::telemetry_set_masking,
            commands::telemetry::telemetry_set_achievement,
            commands::telemetry::telemetry_export,
            commands::telemetry::telemetry_wipe,
            commands::telemetry::telemetry_insights,
            commands::telemetry::telemetry_year_in_review,
            commands::telemetry::telemetry_export_csv,
            commands::telemetry::telemetry_export_wakatime,
            commands::telemetry::telemetry_shareable_card,
            commands::telemetry::telemetry_year_card,
            commands::telemetry::telemetry_evaluate_achievements,
            commands::telemetry::telemetry_idle_seconds,
            commands::telemetry::telemetry_active_window,
            commands::telemetry::webhook_send_digest,
            // discord rich presence
            commands::discord::discord_status,
            commands::discord::discord_apply_settings,
            commands::discord::discord_update,
            commands::discord::discord_push_event,
            commands::discord::discord_clear,
            commands::audit::audit_run,
            commands::metrics::metrics_collect,
            // AI agents / process trees
            commands::agents::agents_sample,
            commands::agents::agents_processes,
            commands::agents::pty_tree_stats,
            // CLI bridge
            commands::cli::cli_poll_requests,
            // window
            commands::window::window_ready,
            commands::window::browser_open_window,
            commands::browser::browser_embed_show,
            commands::browser::browser_embed_set_bounds,
            commands::browser::browser_embed_navigate,
            commands::browser::browser_embed_back,
            commands::browser::browser_embed_forward,
            commands::browser::browser_embed_reload,
            commands::browser::browser_embed_hide,
            commands::browser::browser_embed_close,
            commands::window::window_open_new,
            commands::window::tray_set_projects,
            commands::window::tray_popup_fit,
            commands::window::tray_popup_hide_if_cursor_outside,
            commands::window::quit_app,
            // launcher
            commands::launcher::launcher_open_terminal,
            commands::launcher::launcher_open_file_manager,
            commands::launcher::launcher_open_ide,
            commands::launcher::launcher_detect_ides,
            commands::launcher::launcher_open_default_app,
            commands::launcher::launcher_detect_terminals,
            commands::launcher::launcher_find_executables,
            commands::launcher::launcher_run_executable,
            // AI center
            // v0.5.0: git extras
            commands::git::git_tags,
            commands::git::git_tag_create,
            commands::git::git_tag_delete,
            commands::git::git_push_tag,
            commands::git::git_reflog,
            commands::git::git_cherry_pick,
            commands::git::git_submodules,
            commands::git::git_submodule_update,
            commands::git::git_conflict_paths,
            commands::git::git_conflict_sides,
            commands::git::git_conflict_resolve,
            // v0.5.0: fs / db extras
            commands::fsx::db_query,
            commands::fsx::fs_encodings,
            commands::fsx::fs_detect_encoding,
            commands::fsx::fs_read_text_encoded,
            commands::fsx::fs_write_text_encoded,
            // v0.5.0: search
            commands::github::github_repo,
            commands::github::github_issues,
            commands::github::github_issue_comments,
            commands::github::github_issue_create,
            commands::github::github_comment_add,
            commands::github::github_pulls,
            commands::github::github_pull_create,
            commands::github::github_runs,
            commands::github::update_check,
            commands::extras::search_in_project,
            commands::extras::replace_in_project,
            // v0.5.0: dev tools
            commands::extras::env_files,
            commands::extras::log_files,
            commands::extras::log_tail,
            commands::extras::disk_usage,
            commands::extras::dep_manifests,
            // v0.5.0: notes / snippets / bookmarks / sessions
            commands::extras::note_get,
            commands::extras::note_set,
            commands::extras::snippet_list,
            commands::extras::snippet_save,
            commands::extras::snippet_delete,
            commands::extras::bookmark_list,
            commands::extras::bookmark_toggle,
            commands::extras::bookmark_delete,
            commands::extras::session_list,
            commands::extras::session_save,
            commands::extras::session_delete,
            // v0.5.0: http / registries / vulnerabilities
            commands::extras::http_request,
            commands::extras::registry_search,
            commands::extras::latest_versions,
            commands::extras::osv_check,
            // v0.5.0: docker
            commands::extras::docker_version,
            commands::extras::docker_containers,
            commands::extras::docker_images,
            commands::extras::docker_logs,
            commands::extras::docker_action,
            commands::extras::docker_exec,
            // v0.5.0: processes
            commands::extras::process_tree,
            commands::extras::process_kill,
            // v0.5.0: crash reports
            commands::extras::crash_list,
            commands::extras::frontend_log,
            commands::extras::frontend_log_read,
            commands::extras::frontend_log_clear,
            commands::extras::open_log_folder,
            commands::extras::diag_collect,
            commands::extras::crash_read,
        ])
        .build(tauri::generate_context!())
        .expect("error while building Luxor")
        .run(|app, event| match event {
            tauri::RunEvent::ExitRequested { .. } | tauri::RunEvent::Exit => cleanup_before_exit(app),
            _ => {}
        });
}
